# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'List.ui',
# licensing of 'List.ui' applies.
#
# Created: Mon Sep 16 14:02:35 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 775)
        MainWindow.setMinimumSize(QtCore.QSize(1070, 750))
        MainWindow.setStyleSheet("selection-background-color: rgba(85, 170, 255, 100);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(11, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tab_Main = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_Main.setObjectName("tab_Main")
        self.tab_LO = QtWidgets.QWidget()
        self.tab_LO.setObjectName("tab_LO")
        self.label_ModManagement = QtWidgets.QLabel(self.tab_LO)
        self.label_ModManagement.setGeometry(QtCore.QRect(870, 10, 179, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ModManagement.sizePolicy().hasHeightForWidth())
        self.label_ModManagement.setSizePolicy(sizePolicy)
        self.label_ModManagement.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_ModManagement.setFont(font)
        self.label_ModManagement.setObjectName("label_ModManagement")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_LO)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(860, 140, 52, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_UP = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_UP.sizePolicy().hasHeightForWidth())
        self.button_UP.setSizePolicy(sizePolicy)
        self.button_UP.setMaximumSize(QtCore.QSize(50, 30))
        self.button_UP.setObjectName("button_UP")
        self.verticalLayout.addWidget(self.button_UP)
        self.button_DOWN = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_DOWN.sizePolicy().hasHeightForWidth())
        self.button_DOWN.setSizePolicy(sizePolicy)
        self.button_DOWN.setMaximumSize(QtCore.QSize(50, 30))
        self.button_DOWN.setObjectName("button_DOWN")
        self.verticalLayout.addWidget(self.button_DOWN)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_LO)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(930, 110, 97, 135))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.button_ENABLE = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_ENABLE.sizePolicy().hasHeightForWidth())
        self.button_ENABLE.setSizePolicy(sizePolicy)
        self.button_ENABLE.setMaximumSize(QtCore.QSize(115, 30))
        self.button_ENABLE.setObjectName("button_ENABLE")
        self.verticalLayout_6.addWidget(self.button_ENABLE)
        self.button_UNDO = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_UNDO.sizePolicy().hasHeightForWidth())
        self.button_UNDO.setSizePolicy(sizePolicy)
        self.button_UNDO.setMaximumSize(QtCore.QSize(115, 30))
        self.button_UNDO.setObjectName("button_UNDO")
        self.verticalLayout_6.addWidget(self.button_UNDO)
        self.button_AutoOrder = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_AutoOrder.sizePolicy().hasHeightForWidth())
        self.button_AutoOrder.setSizePolicy(sizePolicy)
        self.button_AutoOrder.setMaximumSize(QtCore.QSize(115, 30))
        self.button_AutoOrder.setObjectName("button_AutoOrder")
        self.verticalLayout_6.addWidget(self.button_AutoOrder)
        self.button_DelteMod = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_DelteMod.sizePolicy().hasHeightForWidth())
        self.button_DelteMod.setSizePolicy(sizePolicy)
        self.button_DelteMod.setMaximumSize(QtCore.QSize(115, 30))
        self.button_DelteMod.setObjectName("button_DelteMod")
        self.verticalLayout_6.addWidget(self.button_DelteMod)
        self.label_LO = QtWidgets.QLabel(self.tab_LO)
        self.label_LO.setGeometry(QtCore.QRect(540, 10, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_LO.sizePolicy().hasHeightForWidth())
        self.label_LO.setSizePolicy(sizePolicy)
        self.label_LO.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_LO.setFont(font)
        self.label_LO.setObjectName("label_LO")
        self.table_InstalledMods = QtWidgets.QTableWidget(self.tab_LO)
        self.table_InstalledMods.setEnabled(False)
        self.table_InstalledMods.setGeometry(QtCore.QRect(60, 40, 321, 351))
        self.table_InstalledMods.setAcceptDrops(False)
        self.table_InstalledMods.setAutoScroll(True)
        self.table_InstalledMods.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_InstalledMods.setTabKeyNavigation(False)
        self.table_InstalledMods.setProperty("showDropIndicator", True)
        self.table_InstalledMods.setDragEnabled(True)
        self.table_InstalledMods.setDragDropOverwriteMode(False)
        self.table_InstalledMods.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.table_InstalledMods.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.table_InstalledMods.setAlternatingRowColors(True)
        self.table_InstalledMods.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.table_InstalledMods.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_InstalledMods.setShowGrid(False)
        self.table_InstalledMods.setGridStyle(QtCore.Qt.DashLine)
        self.table_InstalledMods.setWordWrap(False)
        self.table_InstalledMods.setCornerButtonEnabled(False)
        self.table_InstalledMods.setObjectName("table_InstalledMods")
        self.table_InstalledMods.setColumnCount(1)
        self.table_InstalledMods.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.table_InstalledMods.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_InstalledMods.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_InstalledMods.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_InstalledMods.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_InstalledMods.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_InstalledMods.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_InstalledMods.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.table_InstalledMods.setItem(0, 0, item)
        self.table_InstalledMods.item(0, 0).setText("Test 1")
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.table_InstalledMods.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.table_InstalledMods.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.table_InstalledMods.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.table_InstalledMods.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.table_InstalledMods.setItem(5, 0, item)
        self.table_InstalledMods.horizontalHeader().setVisible(False)
        self.table_InstalledMods.horizontalHeader().setCascadingSectionResizes(True)
        self.table_InstalledMods.horizontalHeader().setDefaultSectionSize(20)
        self.table_InstalledMods.horizontalHeader().setHighlightSections(False)
        self.table_InstalledMods.horizontalHeader().setMinimumSectionSize(20)
        self.table_InstalledMods.horizontalHeader().setSortIndicatorShown(True)
        self.table_InstalledMods.horizontalHeader().setStretchLastSection(True)
        self.table_InstalledMods.verticalHeader().setVisible(False)
        self.table_InstalledMods.verticalHeader().setCascadingSectionResizes(False)
        self.table_InstalledMods.verticalHeader().setDefaultSectionSize(30)
        self.table_InstalledMods.verticalHeader().setMinimumSectionSize(20)
        self.label_DisabledMods = QtWidgets.QLabel(self.tab_LO)
        self.label_DisabledMods.setGeometry(QtCore.QRect(60, 10, 179, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_DisabledMods.sizePolicy().hasHeightForWidth())
        self.label_DisabledMods.setSizePolicy(sizePolicy)
        self.label_DisabledMods.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_DisabledMods.setFont(font)
        self.label_DisabledMods.setObjectName("label_DisabledMods")
        self.tree_LoadOrder = QtWidgets.QTreeWidget(self.tab_LO)
        self.tree_LoadOrder.setEnabled(False)
        self.tree_LoadOrder.setGeometry(QtCore.QRect(540, 40, 311, 351))
        self.tree_LoadOrder.setMinimumSize(QtCore.QSize(50, 20))
        self.tree_LoadOrder.setMaximumSize(QtCore.QSize(9999, 16777215))
        self.tree_LoadOrder.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tree_LoadOrder.setProperty("showDropIndicator", True)
        self.tree_LoadOrder.setDragEnabled(True)
        self.tree_LoadOrder.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tree_LoadOrder.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.tree_LoadOrder.setAlternatingRowColors(True)
        self.tree_LoadOrder.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tree_LoadOrder.setIndentation(0)
        self.tree_LoadOrder.setItemsExpandable(False)
        self.tree_LoadOrder.setAllColumnsShowFocus(True)
        self.tree_LoadOrder.setExpandsOnDoubleClick(False)
        self.tree_LoadOrder.setObjectName("tree_LoadOrder")
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_LoadOrder)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_LoadOrder)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_LoadOrder)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_LoadOrder)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_LoadOrder)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_LoadOrder)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_LoadOrder)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.tree_LoadOrder.header().setCascadingSectionResizes(False)
        self.tree_LoadOrder.header().setDefaultSectionSize(25)
        self.tree_LoadOrder.header().setMinimumSectionSize(25)
        self.tree_LoadOrder.header().setStretchLastSection(True)
        self.tab_Main.addTab(self.tab_LO, "")
        self.verticalLayout_5.addWidget(self.tab_Main)
        self.gridLayout.addLayout(self.verticalLayout_5, 2, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout.addLayout(self.verticalLayout_3, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_Main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.tab_Main.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Test</p><p><br/></p></body></html>", None, -1))
        self.label_ModManagement.setText(QtWidgets.QApplication.translate("MainWindow", "Mod Management:", None, -1))
        self.button_UP.setText(QtWidgets.QApplication.translate("MainWindow", "▲", None, -1))
        self.button_DOWN.setText(QtWidgets.QApplication.translate("MainWindow", "▼", None, -1))
        self.button_ENABLE.setText(QtWidgets.QApplication.translate("MainWindow", "Enable/Disable", None, -1))
        self.button_UNDO.setText(QtWidgets.QApplication.translate("MainWindow", "Undo Last", None, -1))
        self.button_AutoOrder.setText(QtWidgets.QApplication.translate("MainWindow", "Auto order", None, -1))
        self.button_DelteMod.setText(QtWidgets.QApplication.translate("MainWindow", "Delete mod file", None, -1))
        self.label_LO.setText(QtWidgets.QApplication.translate("MainWindow", "Load Order:", None, -1))
        self.table_InstalledMods.setSortingEnabled(True)
        self.table_InstalledMods.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Mod Name", None, -1))
        __sortingEnabled = self.table_InstalledMods.isSortingEnabled()
        self.table_InstalledMods.setSortingEnabled(False)
        self.table_InstalledMods.item(1, 0).setText(QtWidgets.QApplication.translate("MainWindow", "Test2", None, -1))
        self.table_InstalledMods.item(2, 0).setText(QtWidgets.QApplication.translate("MainWindow", "Test 3", None, -1))
        self.table_InstalledMods.item(3, 0).setText(QtWidgets.QApplication.translate("MainWindow", "asdqweasd", None, -1))
        self.table_InstalledMods.item(4, 0).setText(QtWidgets.QApplication.translate("MainWindow", "wasdawe1", None, -1))
        self.table_InstalledMods.item(5, 0).setText(QtWidgets.QApplication.translate("MainWindow", "123asdawe", None, -1))
        self.table_InstalledMods.setSortingEnabled(__sortingEnabled)
        self.label_DisabledMods.setText(QtWidgets.QApplication.translate("MainWindow", "Installed Mods", None, -1))
        self.tree_LoadOrder.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "Mod Name", None, -1))
        __sortingEnabled = self.tree_LoadOrder.isSortingEnabled()
        self.tree_LoadOrder.setSortingEnabled(False)
        self.tree_LoadOrder.topLevelItem(0).setText(0, QtWidgets.QApplication.translate("MainWindow", "Boop", None, -1))
        self.tree_LoadOrder.setSortingEnabled(__sortingEnabled)
        self.tab_Main.setTabText(self.tab_Main.indexOf(self.tab_LO), QtWidgets.QApplication.translate("MainWindow", "Load Order", None, -1))

