# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModManager.ui',
# licensing of 'ModManager.ui' applies.
#
# Created: Tue Sep 17 19:52:11 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 775)
        MainWindow.setMinimumSize(QtCore.QSize(1070, 750))
        MainWindow.setStyleSheet("selection-background-color: rgba(85, 170, 255, 100);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(11, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 1, 1, 3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_A = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_A.sizePolicy().hasHeightForWidth())
        self.label_A.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_A.setFont(font)
        self.label_A.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_A.setObjectName("label_A")
        self.gridLayout_4.addWidget(self.label_A, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radio_DE = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_DE.setEnabled(False)
        self.radio_DE.setObjectName("radio_DE")
        self.DEorClassic = QtWidgets.QButtonGroup(MainWindow)
        self.DEorClassic.setObjectName("DEorClassic")
        self.DEorClassic.addButton(self.radio_DE)
        self.horizontalLayout_3.addWidget(self.radio_DE)
        self.radio_Classic = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_Classic.setEnabled(False)
        self.radio_Classic.setObjectName("radio_Classic")
        self.DEorClassic.addButton(self.radio_Classic)
        self.horizontalLayout_3.addWidget(self.radio_Classic)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.comboBox_Profiles = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Profiles.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Profiles.sizePolicy().hasHeightForWidth())
        self.comboBox_Profiles.setSizePolicy(sizePolicy)
        self.comboBox_Profiles.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_Profiles.setMaximumSize(QtCore.QSize(300, 30))
        self.comboBox_Profiles.setSizeIncrement(QtCore.QSize(0, 0))
        self.comboBox_Profiles.setEditable(False)
        self.comboBox_Profiles.setObjectName("comboBox_Profiles")
        self.gridLayout_4.addWidget(self.comboBox_Profiles, 3, 1, 1, 1)
        self.textbox_UserFolder = QtWidgets.QTextEdit(self.centralwidget)
        self.textbox_UserFolder.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textbox_UserFolder.sizePolicy().hasHeightForWidth())
        self.textbox_UserFolder.setSizePolicy(sizePolicy)
        self.textbox_UserFolder.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textbox_UserFolder.setObjectName("textbox_UserFolder")
        self.gridLayout_4.addWidget(self.textbox_UserFolder, 0, 1, 1, 1)
        self.button_GameFolder = QtWidgets.QToolButton(self.centralwidget)
        self.button_GameFolder.setObjectName("button_GameFolder")
        self.gridLayout_4.addWidget(self.button_GameFolder, 1, 2, 1, 1)
        self.textbox_GameFolder = QtWidgets.QTextEdit(self.centralwidget)
        self.textbox_GameFolder.setEnabled(False)
        self.textbox_GameFolder.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textbox_GameFolder.setObjectName("textbox_GameFolder")
        self.gridLayout_4.addWidget(self.textbox_GameFolder, 1, 1, 1, 1)
        self.label_ActiveProfile = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ActiveProfile.sizePolicy().hasHeightForWidth())
        self.label_ActiveProfile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_ActiveProfile.setFont(font)
        self.label_ActiveProfile.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_ActiveProfile.setObjectName("label_ActiveProfile")
        self.gridLayout_4.addWidget(self.label_ActiveProfile, 3, 0, 1, 1)
        self.label_UserFolder = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_UserFolder.setFont(font)
        self.label_UserFolder.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_UserFolder.setObjectName("label_UserFolder")
        self.gridLayout_4.addWidget(self.label_UserFolder, 0, 0, 1, 1)
        self.label_GameFolder = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_GameFolder.setFont(font)
        self.label_GameFolder.setObjectName("label_GameFolder")
        self.gridLayout_4.addWidget(self.label_GameFolder, 1, 0, 1, 1)
        self.button_UserFolder = QtWidgets.QToolButton(self.centralwidget)
        self.button_UserFolder.setObjectName("button_UserFolder")
        self.gridLayout_4.addWidget(self.button_UserFolder, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 1, 4, 2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tab_Main = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_Main.setObjectName("tab_Main")
        self.tab_LO = QtWidgets.QWidget()
        self.tab_LO.setObjectName("tab_LO")
        self.label_ModManagement = QtWidgets.QLabel(self.tab_LO)
        self.label_ModManagement.setGeometry(QtCore.QRect(870, 10, 179, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ModManagement.sizePolicy().hasHeightForWidth())
        self.label_ModManagement.setSizePolicy(sizePolicy)
        self.label_ModManagement.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_ModManagement.setFont(font)
        self.label_ModManagement.setObjectName("label_ModManagement")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_LO)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(860, 140, 52, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_UP = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_UP.sizePolicy().hasHeightForWidth())
        self.button_UP.setSizePolicy(sizePolicy)
        self.button_UP.setMaximumSize(QtCore.QSize(50, 30))
        self.button_UP.setObjectName("button_UP")
        self.verticalLayout.addWidget(self.button_UP)
        self.button_DOWN = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_DOWN.sizePolicy().hasHeightForWidth())
        self.button_DOWN.setSizePolicy(sizePolicy)
        self.button_DOWN.setMaximumSize(QtCore.QSize(50, 30))
        self.button_DOWN.setObjectName("button_DOWN")
        self.verticalLayout.addWidget(self.button_DOWN)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_LO)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(930, 110, 97, 135))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.button_ENABLE = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_ENABLE.sizePolicy().hasHeightForWidth())
        self.button_ENABLE.setSizePolicy(sizePolicy)
        self.button_ENABLE.setMaximumSize(QtCore.QSize(115, 30))
        self.button_ENABLE.setObjectName("button_ENABLE")
        self.verticalLayout_6.addWidget(self.button_ENABLE)
        self.button_UNDO = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_UNDO.sizePolicy().hasHeightForWidth())
        self.button_UNDO.setSizePolicy(sizePolicy)
        self.button_UNDO.setMaximumSize(QtCore.QSize(115, 30))
        self.button_UNDO.setObjectName("button_UNDO")
        self.verticalLayout_6.addWidget(self.button_UNDO)
        self.button_AutoOrder = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_AutoOrder.sizePolicy().hasHeightForWidth())
        self.button_AutoOrder.setSizePolicy(sizePolicy)
        self.button_AutoOrder.setMaximumSize(QtCore.QSize(115, 30))
        self.button_AutoOrder.setObjectName("button_AutoOrder")
        self.verticalLayout_6.addWidget(self.button_AutoOrder)
        self.button_DelteMod = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_DelteMod.sizePolicy().hasHeightForWidth())
        self.button_DelteMod.setSizePolicy(sizePolicy)
        self.button_DelteMod.setMaximumSize(QtCore.QSize(115, 30))
        self.button_DelteMod.setObjectName("button_DelteMod")
        self.verticalLayout_6.addWidget(self.button_DelteMod)
        self.label_LO = QtWidgets.QLabel(self.tab_LO)
        self.label_LO.setGeometry(QtCore.QRect(540, 10, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_LO.sizePolicy().hasHeightForWidth())
        self.label_LO.setSizePolicy(sizePolicy)
        self.label_LO.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_LO.setFont(font)
        self.label_LO.setObjectName("label_LO")
        self.label_DisabledMods = QtWidgets.QLabel(self.tab_LO)
        self.label_DisabledMods.setGeometry(QtCore.QRect(180, 10, 179, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_DisabledMods.sizePolicy().hasHeightForWidth())
        self.label_DisabledMods.setSizePolicy(sizePolicy)
        self.label_DisabledMods.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_DisabledMods.setFont(font)
        self.label_DisabledMods.setObjectName("label_DisabledMods")
        self.tree_LoadOrder = QtWidgets.QTreeWidget(self.tab_LO)
        self.tree_LoadOrder.setEnabled(False)
        self.tree_LoadOrder.setGeometry(QtCore.QRect(540, 40, 311, 351))
        self.tree_LoadOrder.setMinimumSize(QtCore.QSize(50, 20))
        self.tree_LoadOrder.setMaximumSize(QtCore.QSize(9999, 16777215))
        self.tree_LoadOrder.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tree_LoadOrder.setProperty("showDropIndicator", True)
        self.tree_LoadOrder.setDragEnabled(True)
        self.tree_LoadOrder.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tree_LoadOrder.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.tree_LoadOrder.setAlternatingRowColors(True)
        self.tree_LoadOrder.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tree_LoadOrder.setIndentation(0)
        self.tree_LoadOrder.setItemsExpandable(False)
        self.tree_LoadOrder.setAllColumnsShowFocus(True)
        self.tree_LoadOrder.setExpandsOnDoubleClick(False)
        self.tree_LoadOrder.setObjectName("tree_LoadOrder")
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_LoadOrder)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_LoadOrder)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_LoadOrder)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_LoadOrder)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_LoadOrder)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_LoadOrder)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_LoadOrder)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.tree_LoadOrder.header().setCascadingSectionResizes(False)
        self.tree_LoadOrder.header().setDefaultSectionSize(25)
        self.tree_LoadOrder.header().setMinimumSectionSize(25)
        self.tree_LoadOrder.header().setStretchLastSection(True)
        self.list_InstalledMods = QtWidgets.QListWidget(self.tab_LO)
        self.list_InstalledMods.setGeometry(QtCore.QRect(160, 40, 321, 341))
        self.list_InstalledMods.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.list_InstalledMods.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.list_InstalledMods.setAlternatingRowColors(True)
        self.list_InstalledMods.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_InstalledMods.setMovement(QtWidgets.QListView.Snap)
        self.list_InstalledMods.setObjectName("list_InstalledMods")
        QtWidgets.QListWidgetItem(self.list_InstalledMods)
        self.tab_Main.addTab(self.tab_LO, "")
        self.LO2 = QtWidgets.QWidget()
        self.LO2.setObjectName("LO2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.LO2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(-1, 0, 791, 391))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox = QtWidgets.QToolBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(150, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(500, 16777215))
        self.toolBox.setObjectName("toolBox")
        self.LoadOrder = QtWidgets.QWidget()
        self.LoadOrder.setGeometry(QtCore.QRect(0, 0, 150, 309))
        self.LoadOrder.setObjectName("LoadOrder")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.LoadOrder)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 141, 311))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setSpacing(7)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.combox_LoadOrderList = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combox_LoadOrderList.sizePolicy().hasHeightForWidth())
        self.combox_LoadOrderList.setSizePolicy(sizePolicy)
        self.combox_LoadOrderList.setMinimumSize(QtCore.QSize(0, 30))
        self.combox_LoadOrderList.setMaximumSize(QtCore.QSize(200, 40))
        self.combox_LoadOrderList.setBaseSize(QtCore.QSize(0, 0))
        self.combox_LoadOrderList.setObjectName("combox_LoadOrderList")
        self.combox_LoadOrderList.addItem("")
        self.combox_LoadOrderList.addItem("")
        self.verticalLayout_4.addWidget(self.combox_LoadOrderList)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem1)
        self.button_EnableDisableMods = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_EnableDisableMods.sizePolicy().hasHeightForWidth())
        self.button_EnableDisableMods.setSizePolicy(sizePolicy)
        self.button_EnableDisableMods.setObjectName("button_EnableDisableMods")
        self.verticalLayout_4.addWidget(self.button_EnableDisableMods)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem2)
        self.button_CreateLO = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_CreateLO.sizePolicy().hasHeightForWidth())
        self.button_CreateLO.setSizePolicy(sizePolicy)
        self.button_CreateLO.setObjectName("button_CreateLO")
        self.verticalLayout_4.addWidget(self.button_CreateLO)
        self.button_DeleteLO = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button_DeleteLO.setObjectName("button_DeleteLO")
        self.verticalLayout_4.addWidget(self.button_DeleteLO)
        self.button_SaveLO = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button_SaveLO.setObjectName("button_SaveLO")
        self.verticalLayout_4.addWidget(self.button_SaveLO)
        self.toolBox.addItem(self.LoadOrder, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_2.setObjectName("page_2")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.page_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 10, 141, 191))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_Links = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Links.sizePolicy().hasHeightForWidth())
        self.label_Links.setSizePolicy(sizePolicy)
        self.label_Links.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_Links.setFont(font)
        self.label_Links.setObjectName("label_Links")
        self.verticalLayout_7.addWidget(self.label_Links)
        self.button_OpenFolder = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_OpenFolder.sizePolicy().hasHeightForWidth())
        self.button_OpenFolder.setSizePolicy(sizePolicy)
        self.button_OpenFolder.setObjectName("button_OpenFolder")
        self.verticalLayout_7.addWidget(self.button_OpenFolder)
        self.button_SteamWorkshop = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.button_SteamWorkshop.setObjectName("button_SteamWorkshop")
        self.verticalLayout_7.addWidget(self.button_SteamWorkshop)
        self.button_SteamCollections = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.button_SteamCollections.setObjectName("button_SteamCollections")
        self.verticalLayout_7.addWidget(self.button_SteamCollections)
        self.button_Nexus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.button_Nexus.setObjectName("button_Nexus")
        self.verticalLayout_7.addWidget(self.button_Nexus)
        self.toolBox.addItem(self.page_2, "")
        self.horizontalLayout.addWidget(self.toolBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem3)
        self.table_InstalledMods_2 = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        self.table_InstalledMods_2.setAcceptDrops(False)
        self.table_InstalledMods_2.setAutoScroll(True)
        self.table_InstalledMods_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_InstalledMods_2.setTabKeyNavigation(False)
        self.table_InstalledMods_2.setProperty("showDropIndicator", True)
        self.table_InstalledMods_2.setDragEnabled(True)
        self.table_InstalledMods_2.setDragDropOverwriteMode(False)
        self.table_InstalledMods_2.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.table_InstalledMods_2.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.table_InstalledMods_2.setAlternatingRowColors(True)
        self.table_InstalledMods_2.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.table_InstalledMods_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_InstalledMods_2.setShowGrid(False)
        self.table_InstalledMods_2.setGridStyle(QtCore.Qt.DashLine)
        self.table_InstalledMods_2.setWordWrap(False)
        self.table_InstalledMods_2.setCornerButtonEnabled(False)
        self.table_InstalledMods_2.setObjectName("table_InstalledMods_2")
        self.table_InstalledMods_2.setColumnCount(1)
        self.table_InstalledMods_2.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.table_InstalledMods_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_InstalledMods_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_InstalledMods_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_InstalledMods_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_InstalledMods_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_InstalledMods_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_InstalledMods_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.table_InstalledMods_2.setItem(0, 0, item)
        self.table_InstalledMods_2.item(0, 0).setText("Test 1")
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.table_InstalledMods_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.table_InstalledMods_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.table_InstalledMods_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.table_InstalledMods_2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.table_InstalledMods_2.setItem(5, 0, item)
        self.table_InstalledMods_2.horizontalHeader().setVisible(False)
        self.table_InstalledMods_2.horizontalHeader().setCascadingSectionResizes(True)
        self.table_InstalledMods_2.horizontalHeader().setDefaultSectionSize(20)
        self.table_InstalledMods_2.horizontalHeader().setHighlightSections(False)
        self.table_InstalledMods_2.horizontalHeader().setMinimumSectionSize(20)
        self.table_InstalledMods_2.horizontalHeader().setSortIndicatorShown(True)
        self.table_InstalledMods_2.horizontalHeader().setStretchLastSection(True)
        self.table_InstalledMods_2.verticalHeader().setVisible(False)
        self.table_InstalledMods_2.verticalHeader().setCascadingSectionResizes(False)
        self.table_InstalledMods_2.verticalHeader().setDefaultSectionSize(30)
        self.table_InstalledMods_2.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout.addWidget(self.table_InstalledMods_2)
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(40)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.listWidget.setMovement(QtWidgets.QListView.Snap)
        self.listWidget.setUniformItemSizes(True)
        self.listWidget.setSelectionRectVisible(True)
        self.listWidget.setObjectName("listWidget")
        QtWidgets.QListWidgetItem(self.listWidget)
        QtWidgets.QListWidgetItem(self.listWidget)
        QtWidgets.QListWidgetItem(self.listWidget)
        QtWidgets.QListWidgetItem(self.listWidget)
        self.horizontalLayout.addWidget(self.listWidget)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem4)
        self.tab_Main.addTab(self.LO2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_2.setGeometry(QtCore.QRect(150, 20, 731, 341))
        self.tableWidget_2.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget_2.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 1, item)
        self.tableWidget_2.verticalHeader().setSortIndicatorShown(True)
        self.tab_Main.addTab(self.tab, "")
        self.tab_test = QtWidgets.QWidget()
        self.tab_test.setObjectName("tab_test")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_test)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(29, 29, 981, 351))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.testLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.testLayout.setContentsMargins(0, 0, 0, 0)
        self.testLayout.setObjectName("testLayout")
        self.tab_Main.addTab(self.tab_test, "")
        self.verticalLayout_5.addWidget(self.tab_Main)
        self.gridLayout.addLayout(self.verticalLayout_5, 7, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_Launch = QtWidgets.QPushButton(self.centralwidget)
        self.button_Launch.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.button_Launch.setFont(font)
        self.button_Launch.setObjectName("button_Launch")
        self.verticalLayout_3.addWidget(self.button_Launch)
        self.gridLayout.addLayout(self.verticalLayout_3, 9, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 8, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_Main.setCurrentIndex(3)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label_A.setText(QtWidgets.QApplication.translate("MainWindow", "Mode:", None, -1))
        self.radio_DE.setText(QtWidgets.QApplication.translate("MainWindow", "DE", None, -1))
        self.radio_Classic.setText(QtWidgets.QApplication.translate("MainWindow", "Classic", None, -1))
        self.textbox_UserFolder.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Please select your Larian folder</p></body></html>", None, -1))
        self.textbox_UserFolder.setHtml(QtWidgets.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, -1))
        self.textbox_UserFolder.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "... Documents\\Larian Studios\\", None, -1))
        self.button_GameFolder.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.textbox_GameFolder.setHtml(QtWidgets.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, -1))
        self.textbox_GameFolder.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "... Steam\\steamapps\\common\\Divinity Original Sin 2\\", None, -1))
        self.label_ActiveProfile.setText(QtWidgets.QApplication.translate("MainWindow", "Active profile:", None, -1))
        self.label_UserFolder.setText(QtWidgets.QApplication.translate("MainWindow", "Larian Folder:", None, -1))
        self.label_GameFolder.setText(QtWidgets.QApplication.translate("MainWindow", "Game Folder:", None, -1))
        self.button_UserFolder.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.tab_Main.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Test</p><p><br/></p></body></html>", None, -1))
        self.label_ModManagement.setText(QtWidgets.QApplication.translate("MainWindow", "Mod Management:", None, -1))
        self.button_UP.setText(QtWidgets.QApplication.translate("MainWindow", "▲", None, -1))
        self.button_DOWN.setText(QtWidgets.QApplication.translate("MainWindow", "▼", None, -1))
        self.button_ENABLE.setText(QtWidgets.QApplication.translate("MainWindow", "Enable/Disable", None, -1))
        self.button_UNDO.setText(QtWidgets.QApplication.translate("MainWindow", "Undo Last", None, -1))
        self.button_AutoOrder.setText(QtWidgets.QApplication.translate("MainWindow", "Auto order", None, -1))
        self.button_DelteMod.setText(QtWidgets.QApplication.translate("MainWindow", "Delete mod file", None, -1))
        self.label_LO.setText(QtWidgets.QApplication.translate("MainWindow", "Load Order:", None, -1))
        self.label_DisabledMods.setText(QtWidgets.QApplication.translate("MainWindow", "Installed Mods", None, -1))
        self.tree_LoadOrder.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "Mod Name", None, -1))
        __sortingEnabled = self.tree_LoadOrder.isSortingEnabled()
        self.tree_LoadOrder.setSortingEnabled(False)
        self.tree_LoadOrder.topLevelItem(0).setText(0, QtWidgets.QApplication.translate("MainWindow", "Boop", None, -1))
        self.tree_LoadOrder.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.list_InstalledMods.isSortingEnabled()
        self.list_InstalledMods.setSortingEnabled(False)
        self.list_InstalledMods.item(0).setText(QtWidgets.QApplication.translate("MainWindow", "New Item", None, -1))
        self.list_InstalledMods.setSortingEnabled(__sortingEnabled)
        self.tab_Main.setTabText(self.tab_Main.indexOf(self.tab_LO), QtWidgets.QApplication.translate("MainWindow", "Load Order", None, -1))
        self.combox_LoadOrderList.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Custom LO 1", None, -1))
        self.combox_LoadOrderList.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Custom LO 2", None, -1))
        self.button_EnableDisableMods.setText(QtWidgets.QApplication.translate("MainWindow", "Enable/Disable Mods", None, -1))
        self.button_CreateLO.setText(QtWidgets.QApplication.translate("MainWindow", "Create new LO", None, -1))
        self.button_DeleteLO.setText(QtWidgets.QApplication.translate("MainWindow", "Delete selected LO", None, -1))
        self.button_SaveLO.setText(QtWidgets.QApplication.translate("MainWindow", "Save changes to LO", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.LoadOrder), QtWidgets.QApplication.translate("MainWindow", "Load Order", None, -1))
        self.label_Links.setText(QtWidgets.QApplication.translate("MainWindow", "Links:", None, -1))
        self.button_OpenFolder.setText(QtWidgets.QApplication.translate("MainWindow", "Open LO folder", None, -1))
        self.button_SteamWorkshop.setText(QtWidgets.QApplication.translate("MainWindow", "Workshop", None, -1))
        self.button_SteamCollections.setText(QtWidgets.QApplication.translate("MainWindow", "Collections", None, -1))
        self.button_Nexus.setText(QtWidgets.QApplication.translate("MainWindow", "Nexus", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtWidgets.QApplication.translate("MainWindow", "Useful Links", None, -1))
        self.table_InstalledMods_2.setSortingEnabled(True)
        self.table_InstalledMods_2.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Mod Name", None, -1))
        __sortingEnabled = self.table_InstalledMods_2.isSortingEnabled()
        self.table_InstalledMods_2.setSortingEnabled(False)
        self.table_InstalledMods_2.item(1, 0).setText(QtWidgets.QApplication.translate("MainWindow", "Test2", None, -1))
        self.table_InstalledMods_2.item(2, 0).setText(QtWidgets.QApplication.translate("MainWindow", "Test 3", None, -1))
        self.table_InstalledMods_2.item(3, 0).setText(QtWidgets.QApplication.translate("MainWindow", "asdqweasd", None, -1))
        self.table_InstalledMods_2.item(4, 0).setText(QtWidgets.QApplication.translate("MainWindow", "wasdawe1", None, -1))
        self.table_InstalledMods_2.item(5, 0).setText(QtWidgets.QApplication.translate("MainWindow", "123asdawe", None, -1))
        self.table_InstalledMods_2.setSortingEnabled(__sortingEnabled)
        self.tableWidget.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.tableWidget.verticalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.tableWidget.verticalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.tableWidget.verticalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.tableWidget.verticalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.tableWidget.verticalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "6", None, -1))
        self.tableWidget.verticalHeaderItem(6).setText(QtWidgets.QApplication.translate("MainWindow", "7", None, -1))
        self.tableWidget.verticalHeaderItem(7).setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Names", None, -1))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.item(0, 0).setText(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.tableWidget.item(1, 0).setText(QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.tableWidget.item(2, 0).setText(QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.tableWidget.item(3, 0).setText(QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.tableWidget.item(4, 0).setText(QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.item(0).setText(QtWidgets.QApplication.translate("MainWindow", "1. ", None, -1))
        self.listWidget.item(1).setText(QtWidgets.QApplication.translate("MainWindow", "2. ", None, -1))
        self.listWidget.item(2).setText(QtWidgets.QApplication.translate("MainWindow", "3. ", None, -1))
        self.listWidget.item(3).setText(QtWidgets.QApplication.translate("MainWindow", "4. ", None, -1))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tab_Main.setTabText(self.tab_Main.indexOf(self.LO2), QtWidgets.QApplication.translate("MainWindow", "LO2", None, -1))
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "R1", None, -1))
        self.tableWidget_2.verticalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "R2", None, -1))
        self.tableWidget_2.verticalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "R3", None, -1))
        self.tableWidget_2.verticalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "R4", None, -1))
        self.tableWidget_2.verticalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "R5", None, -1))
        self.tableWidget_2.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "C1", None, -1))
        self.tableWidget_2.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "C2", None, -1))
        self.tableWidget_2.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "C3", None, -1))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.item(0, 0).setText(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.tableWidget_2.item(0, 1).setText(QtWidgets.QApplication.translate("MainWindow", "A", None, -1))
        self.tableWidget_2.item(1, 0).setText(QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.tableWidget_2.item(1, 1).setText(QtWidgets.QApplication.translate("MainWindow", "B", None, -1))
        self.tableWidget_2.item(2, 0).setText(QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.tableWidget_2.item(2, 1).setText(QtWidgets.QApplication.translate("MainWindow", "C", None, -1))
        self.tableWidget_2.item(3, 0).setText(QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.tableWidget_2.item(3, 1).setText(QtWidgets.QApplication.translate("MainWindow", "D", None, -1))
        self.tableWidget_2.item(4, 0).setText(QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.tableWidget_2.item(4, 1).setText(QtWidgets.QApplication.translate("MainWindow", "E", None, -1))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.tab_Main.setTabText(self.tab_Main.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Page", None, -1))
        self.tab_Main.setTabText(self.tab_Main.indexOf(self.tab_test), QtWidgets.QApplication.translate("MainWindow", "Page", None, -1))
        self.button_Launch.setText(QtWidgets.QApplication.translate("MainWindow", "Launch", None, -1))

