# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModManager.ui',
# licensing of 'ModManager.ui' applies.
#
# Created: Wed Sep 25 17:39:27 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 820)
        MainWindow.setMinimumSize(QtCore.QSize(1070, 800))
        MainWindow.setStyleSheet("selection-background-color: rgba(85, 170, 255, 100);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(1280, 800))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(11, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 9, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 7, 1, 1, 3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_Launch = QtWidgets.QPushButton(self.centralwidget)
        self.button_Launch.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.button_Launch.setFont(font)
        self.button_Launch.setObjectName("button_Launch")
        self.verticalLayout_3.addWidget(self.button_Launch)
        self.gridLayout.addLayout(self.verticalLayout_3, 10, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Welcome = QtWidgets.QTabWidget(self.centralwidget)
        self.Welcome.setEnabled(True)
        self.Welcome.setObjectName("Welcome")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Welcome.addTab(self.tab, "")
        self.tab_LO = QtWidgets.QWidget()
        self.tab_LO.setObjectName("tab_LO")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_LO)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1021, 401))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setContentsMargins(15, 15, 15, 15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.toolBox = QtWidgets.QToolBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(175, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(500, 16777215))
        self.toolBox.setObjectName("toolBox")
        self.LoadOrder = QtWidgets.QWidget()
        self.LoadOrder.setGeometry(QtCore.QRect(0, 0, 175, 276))
        self.LoadOrder.setObjectName("LoadOrder")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.LoadOrder)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 177, 311))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setSpacing(7)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_ActiveProfile_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ActiveProfile_2.sizePolicy().hasHeightForWidth())
        self.label_ActiveProfile_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_ActiveProfile_2.setFont(font)
        self.label_ActiveProfile_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_ActiveProfile_2.setObjectName("label_ActiveProfile_2")
        self.verticalLayout_4.addWidget(self.label_ActiveProfile_2)
        self.combo_customlo = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_customlo.sizePolicy().hasHeightForWidth())
        self.combo_customlo.setSizePolicy(sizePolicy)
        self.combo_customlo.setMinimumSize(QtCore.QSize(165, 20))
        self.combo_customlo.setMaximumSize(QtCore.QSize(165, 25))
        self.combo_customlo.setBaseSize(QtCore.QSize(0, 0))
        self.combo_customlo.setObjectName("combo_customlo")
        self.verticalLayout_4.addWidget(self.combo_customlo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem2)
        self.btnCreateLO = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCreateLO.sizePolicy().hasHeightForWidth())
        self.btnCreateLO.setSizePolicy(sizePolicy)
        self.btnCreateLO.setMinimumSize(QtCore.QSize(165, 25))
        self.btnCreateLO.setObjectName("btnCreateLO")
        self.verticalLayout_4.addWidget(self.btnCreateLO)
        self.btnDeleteLO = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeleteLO.sizePolicy().hasHeightForWidth())
        self.btnDeleteLO.setSizePolicy(sizePolicy)
        self.btnDeleteLO.setMinimumSize(QtCore.QSize(165, 0))
        self.btnDeleteLO.setObjectName("btnDeleteLO")
        self.verticalLayout_4.addWidget(self.btnDeleteLO)
        self.saveToLO = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveToLO.sizePolicy().hasHeightForWidth())
        self.saveToLO.setSizePolicy(sizePolicy)
        self.saveToLO.setMinimumSize(QtCore.QSize(165, 0))
        self.saveToLO.setObjectName("saveToLO")
        self.verticalLayout_4.addWidget(self.saveToLO)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem3)
        self.button_EnableDisableMods = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_EnableDisableMods.sizePolicy().hasHeightForWidth())
        self.button_EnableDisableMods.setSizePolicy(sizePolicy)
        self.button_EnableDisableMods.setMinimumSize(QtCore.QSize(165, 0))
        self.button_EnableDisableMods.setObjectName("button_EnableDisableMods")
        self.verticalLayout_4.addWidget(self.button_EnableDisableMods)
        self.btnAddGroup = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddGroup.sizePolicy().hasHeightForWidth())
        self.btnAddGroup.setSizePolicy(sizePolicy)
        self.btnAddGroup.setMinimumSize(QtCore.QSize(165, 25))
        self.btnAddGroup.setObjectName("btnAddGroup")
        self.verticalLayout_4.addWidget(self.btnAddGroup)
        self.toolBox.addItem(self.LoadOrder, "")
        self.Tools = QtWidgets.QWidget()
        self.Tools.setObjectName("Tools")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Tools)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, -10, 181, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnMoveWorkshopFiles = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMoveWorkshopFiles.sizePolicy().hasHeightForWidth())
        self.btnMoveWorkshopFiles.setSizePolicy(sizePolicy)
        self.btnMoveWorkshopFiles.setMinimumSize(QtCore.QSize(165, 0))
        self.btnMoveWorkshopFiles.setObjectName("btnMoveWorkshopFiles")
        self.verticalLayout.addWidget(self.btnMoveWorkshopFiles)
        self.toolBox.addItem(self.Tools, "")
        self.Links = QtWidgets.QWidget()
        self.Links.setGeometry(QtCore.QRect(0, 0, 175, 276))
        self.Links.setObjectName("Links")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.Links)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 10, 167, 233))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_Links = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Links.sizePolicy().hasHeightForWidth())
        self.label_Links.setSizePolicy(sizePolicy)
        self.label_Links.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_Links.setFont(font)
        self.label_Links.setObjectName("label_Links")
        self.verticalLayout_7.addWidget(self.label_Links)
        self.btnOpenFolderMods = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpenFolderMods.sizePolicy().hasHeightForWidth())
        self.btnOpenFolderMods.setSizePolicy(sizePolicy)
        self.btnOpenFolderMods.setMinimumSize(QtCore.QSize(165, 0))
        self.btnOpenFolderMods.setObjectName("btnOpenFolderMods")
        self.verticalLayout_7.addWidget(self.btnOpenFolderMods)
        self.btnOpenWorkshopFolder = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.btnOpenWorkshopFolder.setObjectName("btnOpenWorkshopFolder")
        self.verticalLayout_7.addWidget(self.btnOpenWorkshopFolder)
        self.btnOpenGameFolder = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.btnOpenGameFolder.setObjectName("btnOpenGameFolder")
        self.verticalLayout_7.addWidget(self.btnOpenGameFolder)
        self.button_SteamWorkshop = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.button_SteamWorkshop.setObjectName("button_SteamWorkshop")
        self.verticalLayout_7.addWidget(self.button_SteamWorkshop)
        self.button_SteamCollections = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.button_SteamCollections.setObjectName("button_SteamCollections")
        self.verticalLayout_7.addWidget(self.button_SteamCollections)
        self.button_Nexus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.button_Nexus.setObjectName("button_Nexus")
        self.verticalLayout_7.addWidget(self.button_Nexus)
        self.toolBox.addItem(self.Links, "")
        self.verticalLayout_6.addWidget(self.toolBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, -1, -1, 15)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 5, 1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_4.addWidget(self.plainTextEdit)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 30))
        self.comboBox.setMaximumSize(QtCore.QSize(100, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.treeFinalView = QtWidgets.QTreeWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeFinalView.sizePolicy().hasHeightForWidth())
        self.treeFinalView.setSizePolicy(sizePolicy)
        self.treeFinalView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.treeFinalView.setFrameShape(QtWidgets.QFrame.Box)
        self.treeFinalView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.treeFinalView.setDragEnabled(True)
        self.treeFinalView.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.treeFinalView.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.treeFinalView.setAlternatingRowColors(True)
        self.treeFinalView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeFinalView.setIndentation(0)
        self.treeFinalView.setUniformRowHeights(True)
        self.treeFinalView.setAllColumnsShowFocus(True)
        self.treeFinalView.setObjectName("treeFinalView")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeFinalView)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        self.treeFinalView.header().setVisible(False)
        self.treeFinalView.header().setCascadingSectionResizes(True)
        self.treeFinalView.header().setDefaultSectionSize(25)
        self.treeFinalView.header().setHighlightSections(True)
        self.treeFinalView.header().setMinimumSectionSize(15)
        self.treeFinalView.header().setStretchLastSection(False)
        self.verticalLayout_8.addWidget(self.treeFinalView)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.progressBar = QtWidgets.QProgressBar(self.tab_LO)
        self.progressBar.setGeometry(QtCore.QRect(0, 400, 1021, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.Welcome.addTab(self.tab_LO, "")
        self.verticalLayout_5.addWidget(self.Welcome)
        self.gridLayout.addLayout(self.verticalLayout_5, 8, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.button_UserFolder = QtWidgets.QToolButton(self.centralwidget)
        self.button_UserFolder.setObjectName("button_UserFolder")
        self.gridLayout_4.addWidget(self.button_UserFolder, 0, 2, 1, 1)
        self.label_UserFolder = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_UserFolder.setFont(font)
        self.label_UserFolder.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_UserFolder.setObjectName("label_UserFolder")
        self.gridLayout_4.addWidget(self.label_UserFolder, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radio_DE = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_DE.setEnabled(False)
        self.radio_DE.setObjectName("radio_DE")
        self.DEorClassic = QtWidgets.QButtonGroup(MainWindow)
        self.DEorClassic.setObjectName("DEorClassic")
        self.DEorClassic.addButton(self.radio_DE)
        self.horizontalLayout_3.addWidget(self.radio_DE)
        self.radio_Classic = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_Classic.setEnabled(False)
        self.radio_Classic.setObjectName("radio_Classic")
        self.DEorClassic.addButton(self.radio_Classic)
        self.horizontalLayout_3.addWidget(self.radio_Classic)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.label_A = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_A.sizePolicy().hasHeightForWidth())
        self.label_A.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_A.setFont(font)
        self.label_A.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_A.setObjectName("label_A")
        self.gridLayout_4.addWidget(self.label_A, 2, 0, 1, 1)
        self.button_GameFolder = QtWidgets.QToolButton(self.centralwidget)
        self.button_GameFolder.setObjectName("button_GameFolder")
        self.gridLayout_4.addWidget(self.button_GameFolder, 1, 2, 1, 1)
        self.label_GameFolder = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_GameFolder.setFont(font)
        self.label_GameFolder.setObjectName("label_GameFolder")
        self.gridLayout_4.addWidget(self.label_GameFolder, 1, 0, 1, 1)
        self.textbox_UserFolder = QtWidgets.QTextEdit(self.centralwidget)
        self.textbox_UserFolder.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textbox_UserFolder.sizePolicy().hasHeightForWidth())
        self.textbox_UserFolder.setSizePolicy(sizePolicy)
        self.textbox_UserFolder.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textbox_UserFolder.setObjectName("textbox_UserFolder")
        self.gridLayout_4.addWidget(self.textbox_UserFolder, 0, 1, 1, 1)
        self.label_ActiveProfile = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ActiveProfile.sizePolicy().hasHeightForWidth())
        self.label_ActiveProfile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_ActiveProfile.setFont(font)
        self.label_ActiveProfile.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_ActiveProfile.setObjectName("label_ActiveProfile")
        self.gridLayout_4.addWidget(self.label_ActiveProfile, 3, 0, 1, 1)
        self.textbox_GameFolder = QtWidgets.QTextEdit(self.centralwidget)
        self.textbox_GameFolder.setEnabled(False)
        self.textbox_GameFolder.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textbox_GameFolder.setObjectName("textbox_GameFolder")
        self.gridLayout_4.addWidget(self.textbox_GameFolder, 1, 1, 1, 1)
        self.comboBox_Profiles = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Profiles.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Profiles.sizePolicy().hasHeightForWidth())
        self.comboBox_Profiles.setSizePolicy(sizePolicy)
        self.comboBox_Profiles.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_Profiles.setMaximumSize(QtCore.QSize(300, 30))
        self.comboBox_Profiles.setSizeIncrement(QtCore.QSize(0, 0))
        self.comboBox_Profiles.setEditable(False)
        self.comboBox_Profiles.setObjectName("comboBox_Profiles")
        self.gridLayout_4.addWidget(self.comboBox_Profiles, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 1, 1, 4, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.Welcome.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.button_Launch.setText(QtWidgets.QApplication.translate("MainWindow", "Launch", None, -1))
        self.Welcome.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Test</p><p><br/></p></body></html>", None, -1))
        self.Welcome.setTabText(self.Welcome.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Starting page", None, -1))
        self.label_ActiveProfile_2.setText(QtWidgets.QApplication.translate("MainWindow", "Custom LO:", None, -1))
        self.btnCreateLO.setText(QtWidgets.QApplication.translate("MainWindow", "Create new LO", None, -1))
        self.btnDeleteLO.setText(QtWidgets.QApplication.translate("MainWindow", "Delete selected LO", None, -1))
        self.saveToLO.setText(QtWidgets.QApplication.translate("MainWindow", "Save changes to LO", None, -1))
        self.button_EnableDisableMods.setText(QtWidgets.QApplication.translate("MainWindow", "Enable / Disable", None, -1))
        self.btnAddGroup.setText(QtWidgets.QApplication.translate("MainWindow", "Add group", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.LoadOrder), QtWidgets.QApplication.translate("MainWindow", "Load Order", None, -1))
        self.btnMoveWorkshopFiles.setText(QtWidgets.QApplication.translate("MainWindow", "Move workshop files", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Tools), QtWidgets.QApplication.translate("MainWindow", "Tools", None, -1))
        self.label_Links.setText(QtWidgets.QApplication.translate("MainWindow", "Links:", None, -1))
        self.btnOpenFolderMods.setText(QtWidgets.QApplication.translate("MainWindow", "Open Mods Folder", None, -1))
        self.btnOpenWorkshopFolder.setText(QtWidgets.QApplication.translate("MainWindow", "Open Workshop Folder", None, -1))
        self.btnOpenGameFolder.setText(QtWidgets.QApplication.translate("MainWindow", "Open game folder", None, -1))
        self.button_SteamWorkshop.setText(QtWidgets.QApplication.translate("MainWindow", "Workshop", None, -1))
        self.button_SteamCollections.setText(QtWidgets.QApplication.translate("MainWindow", "Collections", None, -1))
        self.button_Nexus.setText(QtWidgets.QApplication.translate("MainWindow", "Nexus", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Links), QtWidgets.QApplication.translate("MainWindow", "Useful Links", None, -1))
        self.plainTextEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Filter", None, -1))
        self.comboBox.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "Filter by:", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Filter by:", None, -1))
        self.treeFinalView.setSortingEnabled(False)
        self.treeFinalView.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "E", None, -1))
        self.treeFinalView.headerItem().setText(1, QtWidgets.QApplication.translate("MainWindow", "Name", None, -1))
        self.treeFinalView.headerItem().setText(2, QtWidgets.QApplication.translate("MainWindow", "Author", None, -1))
        self.treeFinalView.headerItem().setText(3, QtWidgets.QApplication.translate("MainWindow", "Version", None, -1))
        self.treeFinalView.headerItem().setText(4, QtWidgets.QApplication.translate("MainWindow", "UUID", None, -1))
        self.treeFinalView.headerItem().setText(5, QtWidgets.QApplication.translate("MainWindow", "Folder", None, -1))
        self.treeFinalView.headerItem().setText(6, QtWidgets.QApplication.translate("MainWindow", "Container", None, -1))
        __sortingEnabled = self.treeFinalView.isSortingEnabled()
        self.treeFinalView.setSortingEnabled(False)
        self.treeFinalView.setSortingEnabled(__sortingEnabled)
        self.Welcome.setTabText(self.Welcome.indexOf(self.tab_LO), QtWidgets.QApplication.translate("MainWindow", "Load Order", None, -1))
        self.button_UserFolder.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.label_UserFolder.setText(QtWidgets.QApplication.translate("MainWindow", "Larian Folder:", None, -1))
        self.radio_DE.setText(QtWidgets.QApplication.translate("MainWindow", "DE", None, -1))
        self.radio_Classic.setText(QtWidgets.QApplication.translate("MainWindow", "Classic", None, -1))
        self.label_A.setText(QtWidgets.QApplication.translate("MainWindow", "Mode:", None, -1))
        self.button_GameFolder.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.label_GameFolder.setText(QtWidgets.QApplication.translate("MainWindow", "Game Folder:", None, -1))
        self.textbox_UserFolder.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Please select your Larian folder</p></body></html>", None, -1))
        self.textbox_UserFolder.setHtml(QtWidgets.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, -1))
        self.textbox_UserFolder.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "... Documents\\Larian Studios\\", None, -1))
        self.label_ActiveProfile.setText(QtWidgets.QApplication.translate("MainWindow", "Active profile:", None, -1))
        self.textbox_GameFolder.setHtml(QtWidgets.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, -1))
        self.textbox_GameFolder.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "... Steam\\steamapps\\common\\Divinity Original Sin 2\\", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuSettings.setTitle(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))

